// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys         *ApiKeyDefinition          `json:",omitempty"`
	GroupId         *string                    `json:",omitempty"`
	IncludeCount    *bool                      `json:",omitempty"`
	IntegrationType *string                    `json:",omitempty"`
	ItemsPerPage    *int                       `json:",omitempty"`
	Links           []Link                     `json:",omitempty"`
	PageNum         *int                       `json:",omitempty"`
	Results         []ApiIntegrationViewManual `json:",omitempty"`
	TotalCount      *float64                   `json:",omitempty"`
	Type            *string                    `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// Link is autogenerated from the json schema
type Link struct {
	ApiKeys *ApiKeyDefinition `json:",omitempty"`
	Href    *string           `json:",omitempty"`
	Rel     *string           `json:",omitempty"`
}

// ApiIntegrationViewManual is autogenerated from the json schema
type ApiIntegrationViewManual struct {
	ApiKeys *ApiKeyDefinition `json:",omitempty"`
	Type    *string           `json:",omitempty"`
}
