// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ApiKeys            *ApiKeyDefinition                                           `json:",omitempty"`
	AuthzQueryTemplate *string                                                     `json:",omitempty"`
	BindPassword       *string                                                     `json:",omitempty"`
	BindUsername       *string                                                     `json:",omitempty"`
	CaCertificate      *string                                                     `json:",omitempty"`
	GroupId            *string                                                     `json:",omitempty"`
	Hostname           *string                                                     `json:",omitempty"`
	Links              []Link                                                      `json:",omitempty"`
	Port               *float64                                                    `json:",omitempty"`
	Request            *ApiAtlasNDSLDAPVerifyConnectivityJobRequestParamsView      `json:",omitempty"`
	RequestId          *string                                                     `json:",omitempty"`
	Status             *string                                                     `json:",omitempty"`
	Validations        []ApiAtlasNDSLDAPVerifyConnectivityJobRequestValidationView `json:",omitempty"`
}

// ApiKeyDefinition is autogenerated from the json schema
type ApiKeyDefinition struct {
	PrivateKey *string `json:",omitempty"`
	PublicKey  *string `json:",omitempty"`
}

// Link is autogenerated from the json schema
type Link struct {
	ApiKeys *ApiKeyDefinition `json:",omitempty"`
	Href    *string           `json:",omitempty"`
	Rel     *string           `json:",omitempty"`
}

// ApiAtlasNDSLDAPVerifyConnectivityJobRequestParamsView is autogenerated from the json schema
type ApiAtlasNDSLDAPVerifyConnectivityJobRequestParamsView struct {
	ApiKeys            *ApiKeyDefinition `json:",omitempty"`
	AuthzQueryTemplate *string           `json:",omitempty"`
	BindPassword       *string           `json:",omitempty"`
	BindUsername       *string           `json:",omitempty"`
	CaCertificate      *string           `json:",omitempty"`
	Hostname           *string           `json:",omitempty"`
	Links              []Link            `json:",omitempty"`
	Port               *float64          `json:",omitempty"`
}

// ApiAtlasNDSLDAPVerifyConnectivityJobRequestValidationView is autogenerated from the json schema
type ApiAtlasNDSLDAPVerifyConnectivityJobRequestValidationView struct {
	ApiKeys        *ApiKeyDefinition `json:",omitempty"`
	Status         *string           `json:",omitempty"`
	ValidationType *string           `json:",omitempty"`
}
